#
#+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!
#                                                                       #
#                                 adcirc2ren.py                         # 
#                                                                       #
#+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!+!
#
# Author: Pat Prodanovic, Ph.D., P.Eng.
# 
# Date: Oct 26, 2015
#
# Purpose: Script takes in a mesh in ADCIRC format, and converts it to
# TELEMAC's slf file using stbtel. The same is achieved by using 
# converter.py, which for some reason wouldn't work for me.
#
# Uses: Python2.7.9, Matplotlib v1.4.2, Numpy v1.8.2
#
# Example:
#
# python adcirc2ren.py -i out.grd -o out.slf out.cli
# where:
# -i input adcirc mesh file
# -o output *.slf and *.cli files generated by stbtel
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Global Imports
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
import os,sys                              # system parameters
import subprocess
# 
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# MAIN
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~	
curdir = os.getcwd()
#
# I/O
if len(sys.argv) != 6 :
	print 'Wrong number of Arguments, stopping now...'
	print 'Usage:'
	print 'python adcirc2ren.py -i out.grd -o out.slf out.cli'
	sys.exit()
dummy1 =  sys.argv[1]
adcirc_file = sys.argv[2]
dummy2 = sys.argv[3]
slf_file = sys.argv[4]
cli_file = sys.argv[5]

# create a stbtel cas file for the adcirc2slf converstion
fout = open('adcirc2slf.cas',"w")
fout.write('UNIVERSAL FILE = \'' + str(adcirc_file) + '\'' + '\n')
fout.write('GEOMETRY FILE FOR TELEMAC = \'' + str(slf_file) + '\'' + '\n')
fout.write('BOUNDARY CONDITIONS FILE = \'' + str(cli_file) + '\'' + '\n')
fout.write('ELIMINATION OF BACKWARD DEPENDENCIES = NO' + '\n')
fout.write('MESH GENERATOR = ADCIRC' + '\n')

fout.close()
print curdir
print 'Operating system: ' + os.name

if (os.name == 'posix'):

	# change the directory to python27 folder of the local telemac installation
	os.chdir('/home/user/opentelemac/v7p0r1/scripts/python27')

	# pass the SYSTELCFG system variable
	subprocess.call('export SYSTELCFG=/home/user/opentelemac/v7p0r1/configs/systel.cis-debian.cfg', shell=True)
	
	# runs the stbtel
	cmd_str = 'python runcode.py stbtel -s ' + curdir + '/adcirc2slf.cas'
	subprocess.call(cmd_str, shell=True)
	
	# changes the current dir to pputils default
	os.chdir(curdir)
	
	# deletes the stbtel compiled executable
	os.remove('stbtel')
